import { FileDetail, File, RepoDetails } from "./types";

export const sampleRepo: RepoDetails = {
    "id": 114208211,
    "node_id": "MDEwOlJlcG9zaXRvcnkxMTQyMDgyMTE=",
    "name": "aws-elb-logs-to-elasticsearch",
    "full_name": "lokoArt/aws-elb-logs-to-elasticsearch",
    "private": false,
    "owner": {
        "login": "lokoArt",
        "id": 5484335,
        "node_id": "MDQ6VXNlcjU0ODQzMzU=",
        "avatar_url": "https://avatars.githubusercontent.com/u/5484335?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lokoArt",
        "html_url": "https://github.com/lokoArt",
        "followers_url": "https://api.github.com/users/lokoArt/followers",
        "following_url": "https://api.github.com/users/lokoArt/following{/other_user}",
        "gists_url": "https://api.github.com/users/lokoArt/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lokoArt/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lokoArt/subscriptions",
        "organizations_url": "https://api.github.com/users/lokoArt/orgs",
        "repos_url": "https://api.github.com/users/lokoArt/repos",
        "events_url": "https://api.github.com/users/lokoArt/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lokoArt/received_events",
        "type": "User",
        "site_admin": false
    },
    "html_url": "https://github.com/lokoArt/aws-elb-logs-to-elasticsearch",
    "description": null,
    "fork": true,
    "url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch",
    "forks_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/forks",
    "keys_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/teams",
    "hooks_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/hooks",
    "issue_events_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/events",
    "assignees_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/tags",
    "blobs_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/languages",
    "stargazers_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/stargazers",
    "contributors_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/contributors",
    "subscribers_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/subscribers",
    "subscription_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/subscription",
    "commits_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/merges",
    "archive_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/downloads",
    "issues_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/labels{/name}",
    "releases_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/releases{/id}",
    "deployments_url": "https://api.github.com/repos/lokoArt/aws-elb-logs-to-elasticsearch/deployments",
    "created_at": "2017-12-14T05:51:09Z",
    "updated_at": "2017-12-14T05:51:11Z",
    "pushed_at": "2016-05-21T17:28:11Z",
    "git_url": "git://github.com/lokoArt/aws-elb-logs-to-elasticsearch.git",
    "ssh_url": "git@github.com:lokoArt/aws-elb-logs-to-elasticsearch.git",
    "clone_url": "https://github.com/lokoArt/aws-elb-logs-to-elasticsearch.git",
    "svn_url": "https://github.com/lokoArt/aws-elb-logs-to-elasticsearch",
    "homepage": null,
    "size": 4,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
};

export const sampleFileDetail: FileDetail = {
    "sha": "00c2c28a4cc24cb64176f9952ea252c718240f1d",
    "node_id": "MDQ6QmxvYjIxNTIwMzQ1OTowMGMyYzI4YTRjYzI0Y2I2NDE3NmY5OTUyZWEyNTJjNzE4MjQwZjFk",
    "size": 750,
    "url": "https://api.github.com/repos/lokoArt/xanpool-frontend-assigment/git/blobs/00c2c28a4cc24cb64176f9952ea252c718240f1d",
    "content": "IyB4YW5wb29sLWZyb250ZW5kLWFzc2lnbWVudAoKUGxlYXNlIGltcGxlbWVu\ndCBhIHNpbXBsZSB3ZWJzaXRlIHVzaW5nIFJlYWN0SlMgKyBUeXBlc2NyaXB0\nLCB0aGF0IHdvdWxkIGFsbG93IGRpc3BsYXlpbmcgR2l0aHViIHVzZXIncyBw\ndWJsaWMgcmVwb3NpdG9yaWVzLgpUaGUgbWFpbiBwYWdlIHNob3VsZCBoYXZl\nIGFuIGlucHV0IGFuZCBhbGxvdyBhIHVzZXIgdG8gZW50ZXIgR2l0aHViJ3Mg\ndXNlcm5hbWUuIFRoZSBzZWNvbmQgcGFnZSB3b3VsZCBkaXNwbGF5IGF2YWls\nYWJsZSByZXBvc2l0b3JpZXMgZm9yIHRoZSBlbnRlcmVkIHVzZXIsIGFuZCB0\naGUgdGhyaWQgcGFnZSB3b3VsZCBkaXNwbGF5IHRoZSBsaXN0IG9mIGZpbGVz\nIGluIHRoZSByZXBvICsgUkVBRE1FLm1kIGNvbnRlbnQgb2YgdGhlIHNlbGVj\ndGVkIHJlc3Bvc2l0b3J5LiAKCkFzIGEgcmVzdWx0IHlvdSBjYW4gZWl0aGVy\nIHppcCB3aXRoIHRoZSBwcm9qZWN0IG9yIHNlbmQgdGhlIGxpbmsgdG8gYSBn\naXQgcmVwb3NpdG9yeS4gUGxlYXNlIHByb3ZpZGUgaW5zdHJ1Y3Rpb25zIGhv\ndyB0byBydW4gdGhlIHByb2plY3QuCgpEb24ndCBib3RoZXIgd2l0aCBkZXNp\nZ24uIEhlcmUgYXJlIG1haW4gY3JpdGVyaWFzIGZvciBwcm9qZWN0IGV2YWx1\nYXRpb246CjEpIENvZGUgcXVhbGl0eQoyKSBVc2luZyB0aGUgYmVzdCBwcmFj\ndGljZXMKMykgUHJvamVjdCBzdHJ1Y3R1cmUKNCkgVGVzdCBjb3ZlcmFnZQo1\nKSBBbnkgb3RoZXIgZ29vZCBwcmFjdGljZXMuCgoK\n",
    "encoding": "base64"
};

export const sampleFile: File = {
    "path": "README.md",
    "mode": "100644",
    "type": "blob",
    "sha": "00c2c28a4cc24cb64176f9952ea252c718240f1d",
    "size": 750,
    "url": "https://api.github.com/repos/lokoArt/xanpool-frontend-assigment/git/blobs/00c2c28a4cc24cb64176f9952ea252c718240f1d"
};